"""API Data Transfer Objects (DTOs) for request/response isolation.

These DTOs define the public API contract, hiding internal domain model
fields that should not be client-settable (e.g., memory_id, created_at).
"""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field

from evoeventmem.domain.models import (
    EntityRef,
    EvidenceRef,
    MemoryKind,
    MemoryRecord,
    normalize_memory_content,
)


class V1EvidenceRequest(BaseModel):
    """Evidence reference input for write requests."""

    source_type: str = Field(min_length=1)
    source_id: str = Field(min_length=1)
    locator: str | None = None
    quote: str | None = None

    def to_domain(self) -> EvidenceRef:
        return EvidenceRef(
            source_type=self.source_type,
            source_id=self.source_id,
            locator=self.locator,
            quote=self.quote,
        )


class V1EntityRequest(BaseModel):
    """Entity input for write requests."""

    name: str = Field(min_length=1)
    kind: str | None = None
    role: str | None = None

    def to_domain(self) -> EntityRef:
        return EntityRef(name=self.name, kind=self.kind, role=self.role)


class V1WriteMemoryRequest(BaseModel):
    """Request body for POST /v1/memories.

    Excludes internal fields that are server-generated:
    - memory_id (generated by server)
    - tenant_id (from X-Tenant-Id header)
    - user_id (from X-User-Id header)
    - session_id (from X-Session-Id header)
    - created_at (generated by server)
    - updated_at (generated by server)
    - normalized_content (computed from content)
    """

    kind: str = Field(default="fact", min_length=1)
    content: str = Field(min_length=1)
    entities: list[str | dict[str, Any]] = Field(default_factory=list)
    evidence: list[V1EvidenceRequest] = Field(default_factory=list)
    event_time: datetime | None = None
    valid_from: datetime | None = None
    valid_to: datetime | None = None
    supersedes: list[UUID] | UUID | None = None
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    metadata: dict[str, Any] = Field(default_factory=dict)

    def _normalize_entities(self) -> list[EntityRef]:
        result: list[EntityRef] = []
        for item in self.entities:
            if isinstance(item, str):
                result.append(EntityRef(name=item))
            elif isinstance(item, dict):
                result.append(EntityRef(**item))
        return result

    def to_domain(
        self,
        *,
        memory_id: UUID,
        tenant_id: str,
        user_id: str,
        session_id: str | None,
    ) -> MemoryRecord:
        """Convert DTO to domain model with server-generated fields.

        Raises:
            ValueError: If body contains tenant_id or user_id that differ from scope.
        """
        from datetime import UTC, datetime

        now = datetime.now(UTC)
        
        # Handle supersedes field (can be single UUID or list)
        supersedes_list: list[UUID] = []
        if self.supersedes is not None:
            if isinstance(self.supersedes, UUID):
                supersedes_list = [self.supersedes]
            else:
                supersedes_list = list(self.supersedes)
        
        return MemoryRecord(
            memory_id=memory_id,
            tenant_id=tenant_id,
            user_id=user_id,
            session_id=session_id,
            memory_kind=MemoryKind(self.kind),
            content=self.content,
            normalized_content=normalize_memory_content(self.content),
            entities=self._normalize_entities(),
            evidence_refs=[e.to_domain() for e in self.evidence],
            event_time=self.event_time,
            valid_from=self.valid_from,
            valid_to=self.valid_to,
            supersedes=supersedes_list,
            confidence=self.confidence,
            metadata=self.metadata,
            created_at=now,
            updated_at=now,
        )


class V1EvidenceResponse(BaseModel):
    """Evidence reference output for responses."""

    source_type: str
    source_id: str
    locator: str | None
    quote: str | None

    @classmethod
    def from_domain(cls, evidence: EvidenceRef) -> V1EvidenceResponse:
        return cls(
            source_type=evidence.source_type,
            source_id=evidence.source_id,
            locator=evidence.locator,
            quote=evidence.quote,
        )


class V1MemoryResponse(BaseModel):
    """Memory record output for responses."""

    memory_id: UUID
    tenant_id: str | None = None
    user_id: str
    session_id: str | None = None
    kind: str
    content: str
    entities: list[str]
    evidence: list[V1EvidenceResponse]
    event_time: datetime | None
    valid_from: datetime | None
    valid_to: datetime | None
    supersedes: UUID | None
    confidence: float
    metadata: dict[str, Any]
    created_at: datetime

    @classmethod
    def from_domain(cls, memory: MemoryRecord) -> V1MemoryResponse:
        return cls(
            memory_id=memory.memory_id,
            tenant_id=memory.tenant_id,
            user_id=memory.user_id,
            session_id=memory.session_id,
            kind=memory.memory_kind.value,
            content=memory.content,
            entities=[entity.name for entity in memory.entities],
            evidence=[
                V1EvidenceResponse.from_domain(evidence)
                for evidence in memory.evidence_refs
            ],
            event_time=memory.event_time,
            valid_from=memory.valid_from,
            valid_to=memory.valid_to,
            supersedes=memory.supersedes[0] if memory.supersedes else None,
            confidence=memory.confidence,
            metadata=memory.metadata,
            created_at=memory.created_at,
        )


class V1MemorySearchHitResponse(BaseModel):
    """Search hit output for responses."""

    memory: V1MemoryResponse
    score: float
    reason: str

    @classmethod
    def from_domain(cls, hit: Any) -> V1MemorySearchHitResponse:
        return cls(
            memory=V1MemoryResponse.from_domain(hit.memory),
            score=hit.score,
            reason=hit.reason,
        )


class V1ExplainResponse(BaseModel):
    """Explain output for responses."""

    memory: V1MemoryResponse
    related: list[V1MemoryResponse]


class V1FeedbackRequest(BaseModel):
    """Feedback request body."""

    outcome: str = Field(min_length=1)
    rating: float | None = Field(default=None, ge=0.0, le=1.0)
